backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Homepage'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'slimes'
    label: 'Slimes'
    folder: '_slimes/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Slime name', name: 'title', widget: 'string' }
      - { label: 'Main photo', name: 'photo', widget: 'image', required: false, allow_multiple: false }
      - { label: 'About the slime', name: 'body', widget: 'markdown' }